# Generated by Django 5.2.10 on 2026-02-28 13:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identity', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hod', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_department', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(blank=True, max_length=100, null=True)),
                ('faculty_email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address (e.g., name@gmail.com).')])),
                ('faculty_mobile', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Mobile number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_mobile', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Mobile number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('for_emergency_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_mobile', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Mobile number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('role', models.CharField(choices=[('FACULTY', 'Faculty'), ('HOD', 'Head of Department'), ('HR', 'Human Resources'), ('ADMIN', 'Admin')], db_index=True, max_length=20)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_balance', models.IntegerField(default=12, verbose_name='Casual Leave (CL)')),
                ('el_balance', models.IntegerField(default=10, verbose_name='Earned Leave (EL)')),
                ('ml_balance', models.IntegerField(default=10, verbose_name='Medical Leave (ML)')),
                ('cl_used', models.FloatField(default=0.0)),
                ('el_used', models.FloatField(default=0.0)),
                ('ml_used', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('HOD_APPROVED', 'HOD Approved'), ('HR_APPROVED', 'HR Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('half_day', models.BooleanField(default=False)),
                ('session', models.CharField(choices=[('FULL', 'Full Day'), ('MORNING', 'Morning Session'), ('AFTERNOON', 'Afternoon Session')], default='FULL', max_length=10)),
                ('leave_type', models.CharField(choices=[('CL', 'CL'), ('EL', 'EL'), ('ML', 'ML')], default='CL', max_length=10)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('hod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
