# Generated by Django 5.2.10 on 2026-02-04 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_leaverequest_college'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faculty_profiles', to='lms.college'),
        ),
        migrations.AddIndex(
            model_name='facultyprofile',
            index=models.Index(fields=['role'], name='lms_faculty_role_799357_idx'),
        ),
        migrations.AddIndex(
            model_name='facultyprofile',
            index=models.Index(fields=['college'], name='lms_faculty_college_0b5432_idx'),
        ),
        migrations.AddIndex(
            model_name='facultyprofile',
            index=models.Index(fields=['department'], name='lms_faculty_departm_c110e4_idx'),
        ),
    ]
