# Generated by Django 5.2.10 on 2026-02-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_leaverequest_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('CL', 'Casual Leave (CL)'), ('EL', 'Earned Leave (EL)'), ('ML', 'Medical Leave (ML)'), ('MAT', 'Maternity Leave (MAT)'), ('PAT', 'Paternity Leave (PAT)')], default='CL', max_length=5),
        ),
    ]
