# Generated by Django 5.2.10 on 2026-02-07 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_alter_facultyprofile_college_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='facultyprofile',
            name='lms_faculty_role_799357_idx',
        ),
        migrations.RemoveIndex(
            model_name='facultyprofile',
            name='lms_faculty_college_0b5432_idx',
        ),
        migrations.RemoveIndex(
            model_name='facultyprofile',
            name='lms_faculty_departm_c110e4_idx',
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='department',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.college'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.college'),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='role',
            field=models.CharField(choices=[('FACULTY', 'Faculty'), ('HOD', 'Head of Department'), ('HR', 'Human Resources'), ('ADMIN', 'Admin')], max_length=20),
        ),
    ]
