# Generated by Django 5.2.10 on 2026-02-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_leaverequest_leave_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavebalance',
            old_name='used_leaves',
            new_name='cl_used',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='total_leaves',
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='cl_balance',
            field=models.IntegerField(default=12, verbose_name='Casual Leave (CL)'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='el_balance',
            field=models.IntegerField(default=10, verbose_name='Earned Leave (EL)'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='el_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='ml_balance',
            field=models.IntegerField(default=10, verbose_name='Medical Leave (ML)'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='ml_used',
            field=models.IntegerField(default=0),
        ),
    ]
