# Generated by Django 5.2.10 on 2026-02-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_rename_used_leaves_leavebalance_cl_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='half_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='cl_used',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='el_used',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='ml_used',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('CL', 'CL'), ('EL', 'EL'), ('ML', 'ML')], default='CL', max_length=10),
        ),
    ]
