# Generated by Django 5.2.10 on 2026-02-12 12:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_remove_facultyprofile_lms_faculty_role_799357_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='facultyprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'HR')), fields=('college',), name='unique_hr_per_college'),
        ),
    ]
