# Generated by Django 5.2.10 on 2026-02-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_leaverequest_half_day_alter_leavebalance_cl_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='session',
            field=models.CharField(choices=[('FULL', 'Full Day'), ('MORNING', 'Morning Session'), ('AFTERNOON', 'Afternoon Session')], default='FULL', max_length=10),
        ),
    ]
