# Generated by Django 5.2.10 on 2026-02-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_facultyprofile_unique_hr_per_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='role',
            field=models.CharField(choices=[('FACULTY', 'Faculty'), ('HOD', 'Head of Department'), ('HR', 'Human Resources'), ('ADMIN', 'Admin')], db_index=True, max_length=20),
        ),
    ]
