# Generated by Django 5.2.10 on 2026-02-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_passwordrequest_facultyprofile_emergency_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='faculty_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
