# Generated by Django 5.2.10 on 2026-02-24 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_alter_facultyprofile_emergency_mobile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facultyprofile',
            old_name='emergency_name',
            new_name='for_emergency_name',
        ),
        migrations.RemoveField(
            model_name='facultyprofile',
            name='faculty_password_plain',
        ),
    ]
